version: 0.2

phases:
#   install:
#     runtime-versions:
#       runtime: version
#       runtime: version
#     commands:
#       - command
#       - command
#     finally:
#       - command
#       - command
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build
#   post_build:
#     commands:
#       - command
#       - command
#     finally:
#       - command
#       - command
